package model.component.entities.common;

import java.lang.String;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.StructureDef;
import oracle.jbo.domain.DatumFactory;
import oracle.jbo.domain.DomainAttributeDef;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainStructureDef;
import oracle.jbo.domain.Struct;

import oracle.sql.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 24 11:52:42 BST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustAddressTyp extends Struct {
    static ORADataFactory[] mCustDatFac = null;
    static int[] mSQLTypes = null;
    static DomainStructureDef mStructureDef = null;
    static ORADataFactory fac;

    public CustAddressTyp(Datum value) throws SQLException {
        super(value);
    }

    public CustAddressTyp() throws SQLException {
    }

    public static ORADataFactory getORADataFactory() {
        if (fac == null) {
            class facClass implements ORADataFactory {
                public ORAData create(Datum d, int sql_type_code) throws SQLException {
                    if (d != null) {
                        return new CustAddressTyp(d);
                    }
                    return null;
                }
            }
            fac = new facClass();
        }
        return fac;
    }

    public int[] getAttrSQLTypes() {
        if (mSQLTypes == null) {
            mSQLTypes = buildAttrSQLTypes();
        }
        return mSQLTypes;
    }

    public StructureDef getStructureDef() {
        return mStructureDef;
    }

    public String getColumnType() {
        return "CUST_ADDRESS_TYP";
    }

    public String getStreetAddress() {
        return (String) getAttribute(0);
    }

    public void setStreetAddress(String value) {
        setAttribute(0, value);
    }

    public String getPostalCode() {
        return (String) getAttribute(1);
    }

    public void setPostalCode(String value) {
        setAttribute(1, value);
    }

    public String getCity() {
        return (String) getAttribute(2);
    }

    public void setCity(String value) {
        setAttribute(2, value);
    }

    public String getStateProvince() {
        return (String) getAttribute(3);
    }

    public void setStateProvince(String value) {
        setAttribute(3, value);
    }

    public String getCountryId() {
        return (String) getAttribute(4);
    }

    public void setCountryId(String value) {
        setAttribute(4, value);
    }

    public void initStructureDef() {
        DomainAttributeDef[] attrs = new DomainAttributeDef[5];
        if (mStructureDef == null) {
            attrs[0] =
                new DomainAttributeDef("StreetAddress", "STREET_ADDRESS", 0, String.class, 12, "VARCHAR", -127, 40,
                                       false);
            attrs[1] =
                new DomainAttributeDef("PostalCode", "POSTAL_CODE", 1, String.class, 12, "VARCHAR", -127, 10, false);
            attrs[2] = new DomainAttributeDef("City", "CITY", 2, String.class, 12, "VARCHAR", -127, 30, false);
            attrs[3] =
                new DomainAttributeDef("StateProvince", "STATE_PROVINCE", 3, String.class, 12, "VARCHAR", -127, 10,
                                       false);
            attrs[4] = new DomainAttributeDef("CountryId", "COUNTRY_ID", 4, String.class, 1, "CHAR", -127, 2, false);
            mStructureDef = new DomainStructureDef(attrs);
        }
    }

    public ORADataFactory[] getAttrORADataFactories() {
        if (mCustDatFac == null) {
            mCustDatFac = new ORADataFactory[5];
            mCustDatFac[0] = null;
            mCustDatFac[1] = null;
            mCustDatFac[2] = null;
            mCustDatFac[3] = null;
            mCustDatFac[4] = null;
        }
        return mCustDatFac;
    }
}

